version: "3.9"

services: 
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
    
    env_file:
      - ".env"
    
    volumes:
      - postgres_data:/var/lib/postgres/data
    restart: "unless-stopped"

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "5379:5379"
    restart: "unless-stopped"

  adminer:
    image: adminer:standalone
    container_name: adminer-server
    ports:
      - "8080:8080"
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db

  web:
    container_name: skills-4-hire
    depends_on:
      - redis
      - db
    build: .
    command: >
      sh -c "chmod +x ./build.sh && ./build.sh"
    env_file:
      - .env
    volumes:
      - .:/app

    restart: "unless-stopped"
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    volumes: 
      - .:/app
    container_name: celery-worker
    depends_on:
      - redis
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - .env
    restart: "unless-stopped"
    
  celery-beat:
    build: .
    container_name: celery-beat
    depends_on:
      - redis
    
    restart: "unless-stopped"
    env_file:
      - .env
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - .:/app
      
volumes:
  postgres_data:
  .:
